"""Tests for the V3 causal VIX-HMM module.

These tests pin the two most important invariants:

1. **Causality.** The score at bar `t` must NOT depend on observations
   after bar `t`. The way we verify this: corrupt VIX values strictly
   AFTER bar T and check that scores at bars `<= T` are unchanged.

2. **State labelling.** "Benign" state must always be the one with lower
   mean log(VIX) within each fit window, regardless of how the HMM's
   internal EM labels them.

A failure on either invariant means the strategy could leak future
information or invert its regime classification.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from research.samir_v3.vix_hmm import (
    _build_features,
    _fit_one_window,
    _identify_low_vol_state,
    vix_hmm_regime_score,
)


def _make_vix_fixture(n: int = 1500, seed: int = 42) -> pd.Series:
    """Synthetic VIX path with realistic bimodal behaviour: mostly low
    (~15) with periodic spikes to 40-60. Deterministic via seed.

    This is enough to drive the 2-state HMM into a confident
    classification — we're not testing accuracy, we're testing
    invariants.
    """
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2010-01-01", periods=n, freq="B")
    # Two-state Markov chain over (low, high) VIX states
    states = np.zeros(n, dtype=int)
    state = 0
    for i in range(n):
        if state == 0:
            state = 1 if rng.uniform() < 0.01 else 0
        else:
            state = 0 if rng.uniform() < 0.05 else 1
        states[i] = state
    # Emit log-VIX from state-conditional Gaussian
    log_vix = np.where(states == 0, rng.normal(2.7, 0.15, n), rng.normal(3.5, 0.30, n))
    vix = np.exp(log_vix).clip(5.0, 100.0)
    return pd.Series(vix, index=idx, name="VIX")


# ── Invariant 1: causality ────────────────────────────────────────────────


def test_score_at_t_does_not_depend_on_observations_after_t() -> None:
    """The score at bar T computed on a series of length N must equal the
    score at bar T computed on a series where bars > T are arbitrarily
    different.

    Refit cadence is 252 bars, so we choose T = 1200 (well after the
    first refit) and replace bars > T with garbage values.
    """
    vix = _make_vix_fixture(n=1500, seed=42)
    T = 1200

    # Reference score series
    ref_score = vix_hmm_regime_score(vix, warmup_bars=504, refit_freq_bars=252)
    assert ref_score.notna().sum() > T, "Need ref score defined at bar T"

    # Corrupted series: bars > T replaced with extreme garbage
    corrupted_values = vix.copy().to_numpy()
    rng = np.random.default_rng(99999)
    corrupted_values[T + 1 :] = rng.uniform(60.0, 90.0, size=len(corrupted_values) - T - 1)
    vix_corrupted = pd.Series(corrupted_values, index=vix.index, name=vix.name)
    corrupted_score = vix_hmm_regime_score(vix_corrupted, warmup_bars=504, refit_freq_bars=252)

    # Verify: scores at bars <= T must match (up to floating-point noise).
    # In our implementation, the refit at fit_point uses data[:fit_point]
    # so we expect scores BEFORE the next refit boundary after T to match.
    # The next refit boundary after T=1200 is at fit_point = 504, 756, 1008,
    # 1260; T=1200 is BEFORE the 1260 refit. So scores [504, 1260) are
    # generated by the same fit_point=1008 model and should match.
    ref = ref_score.iloc[:T].to_numpy()
    corr = corrupted_score.iloc[:T].to_numpy()
    max_diff = float(np.nanmax(np.abs(ref - corr)))
    assert max_diff < 1e-9, (
        f"Causality violation: scores at bars <= T={T} differ when future "
        f"VIX is corrupted. max |Δ| = {max_diff:.3e}. The HMM is leaking "
        f"future information into past scores."
    )


# ── Invariant 2: state labelling ──────────────────────────────────────────


def test_low_vol_state_has_lower_mean_log_vix_per_window() -> None:
    """For any IS window, the "low-vol" state identified by
    ``_identify_low_vol_state`` must have lower mean log(VIX) than the
    other state. This must hold regardless of how the EM solver
    happened to number them on a given fit."""
    vix = _make_vix_fixture(n=1500, seed=7)
    feats = _build_features(vix).to_numpy()

    # Fit on first 1000 bars
    model = _fit_one_window(feats[:1000], n_states=2)
    low_state = _identify_low_vol_state(model, feats[:1000])
    other_state = 1 - low_state

    assert model.means_[low_state, 0] < model.means_[other_state, 0], (
        f"low_state={low_state} but its mean log(VIX) "
        f"({model.means_[low_state, 0]:.3f}) is NOT lower than the other "
        f"state's mean ({model.means_[other_state, 0]:.3f}). The state-"
        f"labelling logic is wrong."
    )


def test_score_distribution_is_well_defined() -> None:
    """The score series must be in [0, 1] inclusive and contain NO NaNs
    after the warmup period."""
    vix = _make_vix_fixture(n=1500, seed=13)
    score = vix_hmm_regime_score(vix, warmup_bars=504, refit_freq_bars=252)

    # Skip the pre-warmup neutral region (bars 0..504 should all be 0.5)
    post_warmup = score.iloc[504:]
    assert post_warmup.notna().all(), "Score has NaN values post-warmup"
    assert (post_warmup >= 0.0).all() and (post_warmup <= 1.0).all(), "Score out of [0, 1] range"


# ── Invariant 3: forward-vol discrimination on a bimodal fixture ─────────


def test_hmm_discriminates_high_and_low_vol_regimes_on_fixture() -> None:
    """On a synthetic bimodal VIX series with realistic regime persistence,
    the HMM should classify regimes such that the high-VIX state is
    associated with higher realised vol on average.

    Fixture design (matched to real VIX statistics):
      - Low regime: stay-prob 0.99 → avg duration ~100 bars (calm periods
        last 3-5 months historically).
      - High regime: stay-prob 0.97 → avg duration ~33 bars (vol regimes
        persist 6-8 weeks historically).
      - Clear state separation (log-mean 2.7 vs 3.5 → VIX ~15 vs ~33).
    """
    rng = np.random.default_rng(31337)
    n = 2000  # ~8 years — enough for the rolling fit + a few refits
    idx = pd.date_range("2008-01-01", periods=n, freq="B")
    states = np.zeros(n, dtype=int)
    s = 0
    for i in range(n):
        if s == 0:
            s = 1 if rng.uniform() < 0.01 else 0  # stay 99% in low
        else:
            s = 0 if rng.uniform() < 0.03 else 1  # stay 97% in high
        states[i] = s
    log_vix = np.where(states == 0, rng.normal(2.7, 0.15, n), rng.normal(3.5, 0.30, n))
    vix = pd.Series(np.exp(log_vix).clip(5, 100), index=idx, name="VIX")
    # SPY vol scales with state (0.7%/d in calm, 2.5%/d in stress)
    spy_rets = np.where(states == 0, rng.normal(0.0004, 0.007, n), rng.normal(-0.0002, 0.025, n))
    spy = pd.Series(100.0 * np.cumprod(1.0 + spy_rets), index=idx, name="SPY")

    score = vix_hmm_regime_score(vix, warmup_bars=504, refit_freq_bars=252)
    fwd_vol = (spy.pct_change().shift(-21).rolling(21).std() * np.sqrt(252)).reindex(score.index)
    df = pd.DataFrame({"score": score, "fwd_vol": fwd_vol}).dropna()
    benign_vol = df.loc[df["score"] > 0.5, "fwd_vol"].mean()
    hostile_vol = df.loc[df["score"] <= 0.5, "fwd_vol"].mean()

    ratio = hostile_vol / benign_vol if benign_vol > 0 else float("inf")
    # Real VIX shows ratio ~1.70x; we want at least 1.3x on the fixture
    # to confirm the math isn't broken. Below 1.3 indicates the HMM is
    # collapsing the two states or mis-labelling them.
    assert ratio > 1.3, (
        f"HMM forward-vol discrimination on bimodal fixture: ratio = "
        f"{ratio:.2f}, expected > 1.3. The HMM isn't classifying meaningfully."
    )
