"""labelling.py

Fixes Gemini's critical omission: the exit logic gap.

If labels are generated by Triple Barrier but live exits use a trailing stop
or MA cross, the model is trained on outcomes from a game it is no longer playing.
This module provides:

  1. TripleBarrierLabeller.label() — generates training labels
  2. TripleBarrierLabeller.compute_barriers_for_live_order() — called at order submission
     in Nautilus using the SAME parameters and regime-conditional logic.

The live strategy must call (2) and then manage the position against those exact
barrier levels on every subsequent bar, replicating the labelling logic faithfully.
"""

from typing import Optional

import numpy as np
import pandas as pd
from numba import njit


@njit(cache=True)
def _triple_barrier_core(
    prices: np.ndarray,
    entry_indices: np.ndarray,
    upper_barriers: np.ndarray,   # fractional, e.g. 0.04 = 4%
    lower_barriers: np.ndarray,   # fractional, e.g. 0.02 = 2%
    max_holding: int,
) -> np.ndarray:
    """Numba-compiled inner loop.
    Returns [n_entries x 2]: col 0 = label {1, -1, 0}, col 1 = exit bar index.
    """
    n = len(entry_indices)
    results = np.empty((n, 2), dtype=np.float64)

    for i in range(n):
        ei = entry_indices[i]
        ep = prices[ei]
        ub = upper_barriers[i]
        lb = lower_barriers[i]
        horizon = min(ei + max_holding, len(prices) - 1)

        label = 0.0
        exit_idx = float(horizon)

        for j in range(ei + 1, horizon + 1):
            ret = prices[j] / ep - 1.0
            if ret >= ub:
                label = 1.0
                exit_idx = float(j)
                break
            elif ret <= -lb:
                label = -1.0
                exit_idx = float(j)
                break

        results[i, 0] = label
        results[i, 1] = exit_idx

    return results


class TripleBarrierLabeller:
    """Dynamic triple barrier labelling.

    Barrier widths are:
      upper = vol_multiplier_upper * daily_vol
      lower = vol_multiplier_lower * daily_vol

    Regime-conditional asymmetry (if regimes provided):
      Regime 1 (high vol / trending):  upper *= 1.5,  lower *= 0.7
      Regime 0 (low vol / mean-rev):   no adjustment (symmetric, tighter)

    These multipliers must be reproduced exactly in compute_barriers_for_live_order().
    """

    REGIME_UPPER_SCALE = {0: 1.0, 1: 1.5}
    REGIME_LOWER_SCALE = {0: 1.0, 1: 0.7}

    def __init__(
        self,
        vol_multiplier_upper: float = 2.0,
        vol_multiplier_lower: float = 1.0,
        max_holding_bars: int = 5,
    ):
        self.vol_multiplier_upper = vol_multiplier_upper
        self.vol_multiplier_lower = vol_multiplier_lower
        self.max_holding_bars = max_holding_bars

    # ── Research use ────────────────────────────────────────────────────────

    def label(
        self,
        prices: pd.Series,
        volatility: pd.Series,
        entry_signals: pd.Series,
        regimes: Optional[pd.Series] = None,
    ) -> pd.DataFrame:
        """Generate triple barrier labels for all entry signals.

        Returns DataFrame indexed by entry time with columns:
          label:          1 (upper hit), -1 (lower hit), 0 (time barrier)
          entry_idx:      integer position in prices
          exit_idx:       integer position in prices
          upper_barrier:  fractional barrier size used
          lower_barrier:  fractional barrier size used
        """
        prices_arr = prices.values.astype(np.float64)
        entry_locs = np.where(entry_signals.reindex(prices.index).fillna(False).values)[0]

        if len(entry_locs) == 0:
            return pd.DataFrame(
                columns=["label", "entry_idx", "exit_idx", "upper_barrier", "lower_barrier"]
            )

        vol_at_entry = volatility.reindex(prices.index).values[entry_locs]
        ub = self.vol_multiplier_upper * vol_at_entry
        lb = self.vol_multiplier_lower * vol_at_entry

        if regimes is not None:
            reg_at_entry = regimes.reindex(prices.index).values[entry_locs]
            for regime, u_scale in self.REGIME_UPPER_SCALE.items():
                mask = reg_at_entry == regime
                ub[mask] *= u_scale
                lb[mask] *= self.REGIME_LOWER_SCALE[regime]

        raw = _triple_barrier_core(
            prices_arr,
            entry_locs.astype(np.int64),
            ub,
            lb,
            self.max_holding_bars,
        )

        result = pd.DataFrame(
            {
                "label": raw[:, 0].astype(int),
                "entry_idx": entry_locs,
                "exit_idx": raw[:, 1].astype(int),
                "upper_barrier": ub,
                "lower_barrier": lb,
            },
            index=prices.index[entry_locs],
        )
        return result

    # ── Production use ──────────────────────────────────────────────────────

    def compute_barriers_for_live_order(
        self,
        entry_price: float,
        current_vol: float,
        current_regime: int,
    ) -> dict:
        """Compute live take-profit and stop-loss price levels.

        MUST use identical multiplier logic to label() — this is what closes
        the training/production label alignment gap.

        Returns:
            {
                'take_profit': float,   # price level
                'stop_loss': float,     # price level
                'upper_frac': float,    # fractional distance (for logging)
                'lower_frac': float,
            }
        """
        u_scale = self.REGIME_UPPER_SCALE.get(current_regime, 1.0)
        l_scale = self.REGIME_LOWER_SCALE.get(current_regime, 1.0)

        upper_frac = self.vol_multiplier_upper * current_vol * u_scale
        lower_frac = self.vol_multiplier_lower * current_vol * l_scale

        return {
            "take_profit": entry_price * (1.0 + upper_frac),
            "stop_loss": entry_price * (1.0 - lower_frac),
            "upper_frac": upper_frac,
            "lower_frac": lower_frac,
        }
